/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuas;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PAVILION
 */
public class menuGraph extends javax.swing.JFrame {
    
    //deklarasi
    private int tabIndex = 0;
    private int tabsIndex = 1;
    private double hMenu1 = 10000;
    private double hMenu2 = 10000;
    private double hMenu3 = 15000;
    private double hMenu4 = 15000;
    private double hMenu5 = 15000;
    private double hMenu6 = 20000;
    private double hMenu7 = 5000;
    private double hMenu8 = 5000;
    private double hMenu9 = 5000;
    private double hMenu10 = 10000;
    private double tHargaMenu1 = 0;
    private double tHargaMenu2 = 0;
    private double tHargaMenu3 = 0;
    private double tHargaMenu4 = 0;
    private double tHargaMenu5 = 0;
    private double tHargaMenu6 = 0;
    private double tHargaMenu7 = 0;
    private double tHargaMenu8 = 0;
    private double tHargaMenu9 = 0;
    private double tHargaMenu10 = 0;
    private double resTotal = 0;
    private double resKembalian = 0;

    

    /**
     * Creates new form menuGraph
     */
    public menuGraph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        contPesanan1 = new javax.swing.JPanel();
        contPesanan2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesananMenu = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pesananJumlah = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        pesananTotal = new javax.swing.JTextArea();
        buttom = new javax.swing.JPanel();
        btnTabPrev = new javax.swing.JButton();
        btnTab1 = new javax.swing.JButton();
        btnTab2 = new javax.swing.JButton();
        btnTabNext = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        left = new javax.swing.JPanel();
        tabMenu = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        menu1 = new javax.swing.JLabel();
        cbMenu1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        inpJumMenu1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        cbMenu2 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        inpJumMenu2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        menu4 = new javax.swing.JLabel();
        cbMenu4 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        inpJumMenu4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        menu6 = new javax.swing.JLabel();
        cbMenu6 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        inpJumMenu6 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        menu5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cbMenu5 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        inpJumMenu5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        menu3 = new javax.swing.JLabel();
        cbMenu3 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        inpJumMenu3 = new javax.swing.JTextField();
        tab2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        menu7 = new javax.swing.JLabel();
        cbMenu7 = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        inpJumMenu7 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        menu8 = new javax.swing.JLabel();
        cbMenu8 = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        inpJumMenu8 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        menu10 = new javax.swing.JLabel();
        cbMenu10 = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        inpJumMenu10 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        menu9 = new javax.swing.JLabel();
        cbMenu9 = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        inpJumMenu9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top.setBackground(new java.awt.Color(234, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("DAFTAR MENU KEDAI MASSE");

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setForeground(new java.awt.Color(0, 51, 102));
        btnClose.setText("KELUAR");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(42, 42, 42))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(topLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 70));

        contPesanan1.setBackground(new java.awt.Color(234, 255, 255));

        contPesanan2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("PESANAN");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("PEMBAYARAN");

        bayar.setBackground(new java.awt.Color(255, 255, 255));
        bayar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bayar.setForeground(new java.awt.Color(0, 51, 102));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Uang Bayar");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Kembalian");

        kembalian.setEditable(false);
        kembalian.setBackground(new java.awt.Color(255, 255, 255));
        kembalian.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        kembalian.setForeground(new java.awt.Color(0, 51, 102));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pesananMenu.setEditable(false);
        pesananMenu.setBackground(new java.awt.Color(255, 255, 255));
        pesananMenu.setColumns(20);
        pesananMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pesananMenu.setForeground(new java.awt.Color(0, 51, 102));
        pesananMenu.setLineWrap(true);
        pesananMenu.setRows(5);
        pesananMenu.setAutoscrolls(false);
        jScrollPane1.setViewportView(pesananMenu);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("TOTAL");

        total.setEditable(false);
        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(0, 51, 102));

        jScrollPane2.setBorder(null);

        pesananJumlah.setEditable(false);
        pesananJumlah.setBackground(new java.awt.Color(255, 255, 255));
        pesananJumlah.setColumns(20);
        pesananJumlah.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pesananJumlah.setForeground(new java.awt.Color(0, 51, 102));
        pesananJumlah.setLineWrap(true);
        pesananJumlah.setRows(5);
        pesananJumlah.setAutoscrolls(false);
        jScrollPane2.setViewportView(pesananJumlah);

        jScrollPane3.setBorder(null);

        pesananTotal.setEditable(false);
        pesananTotal.setBackground(new java.awt.Color(255, 255, 255));
        pesananTotal.setColumns(20);
        pesananTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pesananTotal.setForeground(new java.awt.Color(0, 51, 102));
        pesananTotal.setLineWrap(true);
        pesananTotal.setRows(5);
        pesananTotal.setAutoscrolls(false);
        jScrollPane3.setViewportView(pesananTotal);

        javax.swing.GroupLayout contPesanan2Layout = new javax.swing.GroupLayout(contPesanan2);
        contPesanan2.setLayout(contPesanan2Layout);
        contPesanan2Layout.setHorizontalGroup(
            contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contPesanan2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contPesanan2Layout.createSequentialGroup()
                        .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contPesanan2Layout.createSequentialGroup()
                        .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contPesanan2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(contPesanan2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contPesanan2Layout.createSequentialGroup()
                                .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16))))
        );
        contPesanan2Layout.setVerticalGroup(
            contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contPesanan2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contPesanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout contPesanan1Layout = new javax.swing.GroupLayout(contPesanan1);
        contPesanan1.setLayout(contPesanan1Layout);
        contPesanan1Layout.setHorizontalGroup(
            contPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contPesanan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contPesanan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        contPesanan1Layout.setVerticalGroup(
            contPesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contPesanan1Layout.createSequentialGroup()
                .addComponent(contPesanan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(contPesanan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 330, -1));

        buttom.setBackground(new java.awt.Color(234, 255, 255));

        btnTabPrev.setBackground(new java.awt.Color(255, 255, 255));
        btnTabPrev.setForeground(new java.awt.Color(0, 51, 102));
        btnTabPrev.setText("<");
        btnTabPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabPrevActionPerformed(evt);
            }
        });

        btnTab1.setBackground(new java.awt.Color(255, 255, 255));
        btnTab1.setForeground(new java.awt.Color(0, 51, 102));
        btnTab1.setText("1");
        btnTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab1ActionPerformed(evt);
            }
        });

        btnTab2.setBackground(new java.awt.Color(255, 255, 255));
        btnTab2.setForeground(new java.awt.Color(0, 51, 102));
        btnTab2.setText("2");
        btnTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab2ActionPerformed(evt);
            }
        });

        btnTabNext.setBackground(new java.awt.Color(255, 255, 255));
        btnTabNext.setForeground(new java.awt.Color(0, 51, 102));
        btnTabNext.setText(">");
        btnTabNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabNextActionPerformed(evt);
            }
        });

        btnBayar.setBackground(new java.awt.Color(102, 255, 102));
        btnBayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 51, 51));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnConfirm.setBackground(new java.awt.Color(51, 153, 255));
        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("KONFIRMASI PESANAN");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttomLayout = new javax.swing.GroupLayout(buttom);
        buttom.setLayout(buttomLayout);
        buttomLayout.setHorizontalGroup(
            buttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnTabPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTab2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTabNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addGap(335, 335, 335))
        );
        buttomLayout.setVerticalGroup(
            buttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTabPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTabNext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 970, 70));

        left.setBackground(new java.awt.Color(234, 255, 255));

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 570));

        tab1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N

        menu1.setBackground(new java.awt.Color(0, 51, 102));
        menu1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu1.setForeground(new java.awt.Color(0, 51, 102));
        menu1.setText("Nasi goreng");

        cbMenu1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("10.000");

        inpJumMenu1.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu1KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Jumlah");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menu1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inpJumMenu1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu1)
                    .addComponent(cbMenu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(inpJumMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N

        menu2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu2.setForeground(new java.awt.Color(0, 51, 102));
        menu2.setText("Mie Goreng");

        cbMenu2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 102));
        jLabel19.setText("10.000");

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setText("Jumlah");

        inpJumMenu2.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(menu2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu2))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inpJumMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu2)
                    .addComponent(cbMenu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(inpJumMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.png"))); // NOI18N
        jLabel15.setText("jLabel15");

        menu4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu4.setForeground(new java.awt.Color(0, 51, 102));
        menu4.setText("Ayam Goreng");

        jLabel25.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 102));
        jLabel25.setText("15.000");

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 102));
        jLabel26.setText("Jumlah");

        inpJumMenu4.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu4KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(menu4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(inpJumMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu4)
                    .addComponent(cbMenu4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(inpJumMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.png"))); // NOI18N

        menu6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu6.setForeground(new java.awt.Color(0, 51, 102));
        menu6.setText("Nasi Ayam");

        jLabel31.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 51, 102));
        jLabel31.setText("20.000");

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 51, 102));
        jLabel32.setText("Jumlah");

        inpJumMenu6.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu6KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(menu6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inpJumMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu6)
                    .addComponent(cbMenu6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(inpJumMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5.png"))); // NOI18N

        menu5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu5.setForeground(new java.awt.Color(0, 51, 102));
        menu5.setText("Ikan Goreng");

        jLabel28.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 102));
        jLabel28.setText("15.000");

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 102));
        jLabel29.setText("Jumlah");

        inpJumMenu5.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(menu5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inpJumMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu5)
                    .addComponent(cbMenu5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(inpJumMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N

        menu3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu3.setForeground(new java.awt.Color(0, 51, 102));
        menu3.setText("Nasi Udang");

        cbMenu3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 102));
        jLabel22.setText("15.000");

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 102));
        jLabel23.setText("Jumlah");

        inpJumMenu3.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu3KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(menu3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu3))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inpJumMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu3)
                    .addComponent(cbMenu3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(inpJumMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        tabMenu.addTab("tab1", tab1);

        tab2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7.png"))); // NOI18N

        menu7.setBackground(new java.awt.Color(0, 51, 102));
        menu7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu7.setForeground(new java.awt.Color(0, 51, 102));
        menu7.setText("Teh Panas");

        cbMenu7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel35.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 51, 102));
        jLabel35.setText("5.000");

        inpJumMenu7.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu7KeyTyped(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 51, 102));
        jLabel36.setText("Jumlah");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(menu7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu7))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inpJumMenu7))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu7)
                    .addComponent(cbMenu7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(inpJumMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/8.png"))); // NOI18N

        menu8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu8.setForeground(new java.awt.Color(0, 51, 102));
        menu8.setText("Es Jeruk");

        cbMenu8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel39.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 51, 102));
        jLabel39.setText("5.000");

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 51, 102));
        jLabel40.setText("Jumlah");

        inpJumMenu8.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu8KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(menu8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu8))
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inpJumMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu8)
                    .addComponent(cbMenu8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(inpJumMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/10.png"))); // NOI18N
        jLabel41.setText("jLabel15");

        menu10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu10.setForeground(new java.awt.Color(0, 51, 102));
        menu10.setText("Kopi Cappuccino");

        jLabel43.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 51, 102));
        jLabel43.setText("10.000");

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 51, 102));
        jLabel44.setText("Jumlah");

        inpJumMenu10.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu10KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(menu10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu10))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(inpJumMenu10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu10)
                    .addComponent(cbMenu10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(inpJumMenu10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9.png"))); // NOI18N

        menu9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menu9.setForeground(new java.awt.Color(0, 51, 102));
        menu9.setText("Es Teh");

        cbMenu9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel55.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 51, 102));
        jLabel55.setText("5.000");

        jLabel56.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 51, 102));
        jLabel56.setText("Jumlah");

        inpJumMenu9.setBackground(new java.awt.Color(255, 255, 255));
        inpJumMenu9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inpJumMenu9KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(menu9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMenu9))
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inpJumMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu9)
                    .addComponent(cbMenu9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(inpJumMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        tabMenu.addTab("tab2", tab2);

        getContentPane().add(tabMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkTyping(java.awt.event.KeyEvent evt){
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }
    
    private void alertInpJumlah(){
        String listAlertInpJum = "";
        if (cbMenu1.isSelected() && inpJumMenu1.getText().isEmpty()) {
            listAlertInpJum += menu1.getText() + ", ";
        }
        if (cbMenu2.isSelected() && inpJumMenu2.getText().isEmpty()) {
            listAlertInpJum += menu2.getText() + ", ";
        }
        if (cbMenu3.isSelected() && inpJumMenu3.getText().isEmpty()) {
            listAlertInpJum += menu3.getText() + ", ";
        }
        if (cbMenu4.isSelected() && inpJumMenu4.getText().isEmpty()) {
            listAlertInpJum += menu4.getText() + ", ";
        }
        if (cbMenu5.isSelected() && inpJumMenu5.getText().isEmpty()) {
            listAlertInpJum += menu5.getText() + ", ";
        }
        if (cbMenu6.isSelected() && inpJumMenu6.getText().isEmpty()) {
            listAlertInpJum += menu6.getText() + ", ";
        }
        if (cbMenu7.isSelected() && inpJumMenu7.getText().isEmpty()) {
            listAlertInpJum += menu7.getText() + ", ";
        }
        if (cbMenu8.isSelected() && inpJumMenu8.getText().isEmpty()) {
            listAlertInpJum += menu8.getText() + ", ";
        }
        if (cbMenu9.isSelected() && inpJumMenu9.getText().isEmpty()) {
            listAlertInpJum += menu1.getText() + ", ";
        }
        if (cbMenu10.isSelected() && inpJumMenu10.getText().isEmpty()) {
            listAlertInpJum += menu10.getText() + ", ";
        }
        
        JOptionPane.showMessageDialog(null, "Mohon isi jumlah pesanan untuk menu : \n" + listAlertInpJum, 
                "Peringatan", JOptionPane.WARNING_MESSAGE);

    }
    
    private boolean checkInpJumlah(){
        if(cbMenu1.isSelected() && inpJumMenu1.getText().isEmpty()||
                cbMenu2.isSelected() && inpJumMenu2.getText().isEmpty()||
                cbMenu3.isSelected() && inpJumMenu3.getText().isEmpty()||
                cbMenu4.isSelected() && inpJumMenu4.getText().isEmpty()||
                cbMenu5.isSelected() && inpJumMenu5.getText().isEmpty()||
                cbMenu6.isSelected() && inpJumMenu6.getText().isEmpty()||
                cbMenu7.isSelected() && inpJumMenu7.getText().isEmpty()||
                cbMenu8.isSelected() && inpJumMenu8.getText().isEmpty()||
                cbMenu9.isSelected() && inpJumMenu9.getText().isEmpty()||
                cbMenu10.isSelected() && inpJumMenu10.getText().isEmpty()){
            return true;
        }
        return false;
    }
    
    private boolean checkCBMenu(){
        if(!cbMenu1.isSelected()&&
                !cbMenu2.isSelected()&&
                !cbMenu3.isSelected()&&
                !cbMenu4.isSelected()&&
                !cbMenu5.isSelected()&&
                !cbMenu6.isSelected()&&
                !cbMenu7.isSelected()&&
                !cbMenu8.isSelected()&&
                !cbMenu9.isSelected()&&
                !cbMenu10.isSelected()){
            return true;
        }
        return false;
    }
    
    private double countTotal(){
        tHargaMenu1 = cbMenu1.isSelected() ? Integer.parseInt(inpJumMenu1.getText()) * hMenu1 : 0;
        tHargaMenu2 = cbMenu2.isSelected() ? Integer.parseInt(inpJumMenu2.getText()) * hMenu2 : 0;
        tHargaMenu3 = cbMenu3.isSelected() ? Integer.parseInt(inpJumMenu3.getText()) * hMenu3 : 0;
        tHargaMenu4 = cbMenu4.isSelected() ? Integer.parseInt(inpJumMenu4.getText()) * hMenu4 : 0;
        tHargaMenu5 = cbMenu5.isSelected() ? Integer.parseInt(inpJumMenu5.getText()) * hMenu5 : 0;
        tHargaMenu6 = cbMenu6.isSelected() ? Integer.parseInt(inpJumMenu6.getText()) * hMenu6 : 0;
        tHargaMenu7 = cbMenu7.isSelected() ? Integer.parseInt(inpJumMenu7.getText()) * hMenu7 : 0;
        tHargaMenu8 = cbMenu8.isSelected() ? Integer.parseInt(inpJumMenu8.getText()) * hMenu8 : 0;
        tHargaMenu9 = cbMenu9.isSelected() ? Integer.parseInt(inpJumMenu9.getText()) * hMenu9 : 0;
        tHargaMenu10 = cbMenu10.isSelected() ? Integer.parseInt(inpJumMenu10.getText()) * hMenu10 : 0;
        return tHargaMenu1 + tHargaMenu2 + tHargaMenu3 + tHargaMenu4 + tHargaMenu5 + tHargaMenu6 + tHargaMenu7
                + tHargaMenu8 + tHargaMenu9 + tHargaMenu10;
    }
    
    private void printPesanan(){
        pesananMenu.setText("");
        pesananJumlah.setText("");
        pesananTotal.setText("");
        
        if (cbMenu1.isSelected()) {
            pesananMenu.append(menu1.getText() + "\n");
            pesananJumlah.append(inpJumMenu1.getText() + "\n");
            pesananTotal.append(tHargaMenu1 + "\n");
        }
        if (cbMenu2.isSelected()) {
            pesananMenu.append(menu2.getText() + "\n");
            pesananJumlah.append(inpJumMenu2.getText() + "\n");
            pesananTotal.append(tHargaMenu2 + "\n");
        }
        if (cbMenu3.isSelected()) {
            pesananMenu.append(menu3.getText() + "\n");
            pesananJumlah.append(inpJumMenu3.getText() + "\n");
            pesananTotal.append(tHargaMenu3 + "\n");
        }
        if (cbMenu4.isSelected()) {
            pesananMenu.append(menu4.getText() + "\n");
            pesananJumlah.append(inpJumMenu4.getText() + "\n");
            pesananTotal.append(tHargaMenu4 + "\n");
        }
        if (cbMenu5.isSelected()) {
            pesananMenu.append(menu5.getText() + "\n");
            pesananJumlah.append(inpJumMenu5.getText() + "\n");
            pesananTotal.append(tHargaMenu5 + "\n");
        }
        if (cbMenu6.isSelected()) {
            pesananMenu.append(menu6.getText() + "\n");
            pesananJumlah.append(inpJumMenu6.getText() + "\n");
            pesananTotal.append(tHargaMenu6 + "\n");
        }
        if (cbMenu7.isSelected()) {
            pesananMenu.append(menu7.getText() + "\n");
            pesananJumlah.append(inpJumMenu7.getText() + "\n");
            pesananTotal.append(tHargaMenu7 + "\n");
        }
        if (cbMenu8.isSelected()) {
            pesananMenu.append(menu8.getText() + "\n");
            pesananJumlah.append(inpJumMenu8.getText() + "\n");
            pesananTotal.append(tHargaMenu8 + "\n");
        }
        if (cbMenu9.isSelected()) {
            pesananMenu.append(menu9.getText() + "\n");
            pesananJumlah.append(inpJumMenu9.getText() + "\n");
            pesananTotal.append(tHargaMenu9 + "\n");
        }
        if (cbMenu10.isSelected()) {
            pesananMenu.append(menu10.getText() + "\n");
            pesananJumlah.append(inpJumMenu10.getText() + "\n");
            pesananTotal.append(tHargaMenu10 + "\n");
        }
    }

    
    private void btnTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab1ActionPerformed
        // TODO add your handling code here:
        tabIndex = 0;
        tabMenu.setSelectedIndex(tabIndex);
        
    }//GEN-LAST:event_btnTab1ActionPerformed

    private void btnTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab2ActionPerformed
        // TODO add your handling code here:
        tabIndex = 1;
        tabMenu.setSelectedIndex(tabIndex);
    }//GEN-LAST:event_btnTab2ActionPerformed

    private void btnTabNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabNextActionPerformed
        // TODO add your handling code here:
        if(tabIndex != tabsIndex){
            tabIndex++;
            tabMenu.setSelectedIndex(tabIndex);
            }
    }//GEN-LAST:event_btnTabNextActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        if(pesananMenu.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Konfirmasi Pemesanan Dahulu", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
        }else if( bayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan Uang pembayaran Terlebih Dahulu", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if(!bayar.getText().isEmpty()){
            double inpBayar = Double.parseDouble(bayar.getText());
            if(inpBayar >= resTotal){
                resKembalian = inpBayar - resTotal;
                kembalian.setText(String.valueOf(resKembalian));                
            }else{
                JOptionPane.showMessageDialog(null, "Uang Pembayaran Tidak Mencukupi", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tHargaMenu1 = 0;
        tHargaMenu2 = 0;
        tHargaMenu3 = 0;
        tHargaMenu4 = 0;
        tHargaMenu5 = 0;
        tHargaMenu6 = 0;
        tHargaMenu7 = 0;
        tHargaMenu8 = 0;
        tHargaMenu9 = 0;
        tHargaMenu10 = 0;
        resTotal = 0;
        resKembalian = 0;
        pesananMenu.setText("");
        pesananJumlah.setText("");
        pesananTotal.setText("");
        total.setText("");
        bayar.setText("");
        kembalian.setText("");
        inpJumMenu1.setText("");
        inpJumMenu2.setText("");
        inpJumMenu3.setText("");
        inpJumMenu4.setText("");
        inpJumMenu5.setText("");
        inpJumMenu6.setText("");
        inpJumMenu7.setText("");
        inpJumMenu8.setText("");
        inpJumMenu9.setText("");
        inpJumMenu10.setText("");
        cbMenu1.setSelected(false);
        cbMenu2.setSelected(false);
        cbMenu3.setSelected(false);
        cbMenu4.setSelected(false);
        cbMenu5.setSelected(false);
        cbMenu6.setSelected(false);
        cbMenu7.setSelected(false);
        cbMenu8.setSelected(false);
        cbMenu9.setSelected(false);
        cbMenu10.setSelected(false);
        JOptionPane.showMessageDialog(null, "Berhasil Melakukan Reset", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int exiting = JOptionPane.showConfirmDialog(null,
            "Keluar Aplikasi?");
        if (exiting == JOptionPane.YES_OPTION) {
          System.exit(0);
        } 
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        boolean statusInpJumlah = checkInpJumlah();  
        boolean statusCBMenu = checkCBMenu();
        if(statusCBMenu == true){
            JOptionPane.showMessageDialog(null, "Mohon pilih menu terlebih dahulu", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
        }else if(statusInpJumlah == true){
            alertInpJumlah();
        }else{
            resTotal = countTotal();
            total.setText(String.valueOf(resTotal));
            printPesanan();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnTabPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabPrevActionPerformed
        // TODO add your handling code here:
        if(tabIndex != 0){
            tabIndex--;
            tabMenu.setSelectedIndex(tabIndex);
            System.out.println(tabIndex);
        }
        
    }//GEN-LAST:event_btnTabPrevActionPerformed

    private void inpJumMenu1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu1KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu1KeyTyped

    private void inpJumMenu2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu2KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu2KeyTyped

    private void inpJumMenu3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu3KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu3KeyTyped

    private void inpJumMenu4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu4KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu4KeyTyped

    private void inpJumMenu5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu5KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu5KeyTyped

    private void inpJumMenu6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu6KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu6KeyTyped

    private void inpJumMenu7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu7KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu7KeyTyped

    private void inpJumMenu8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu8KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu8KeyTyped

    private void inpJumMenu9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu9KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu9KeyTyped

    private void inpJumMenu10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumMenu10KeyTyped
        // TODO add your handling code here:
        checkTyping(evt);
    }//GEN-LAST:event_inpJumMenu10KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGraph().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTab1;
    private javax.swing.JButton btnTab2;
    private javax.swing.JButton btnTabNext;
    private javax.swing.JButton btnTabPrev;
    private javax.swing.JPanel buttom;
    private javax.swing.JCheckBox cbMenu1;
    private javax.swing.JCheckBox cbMenu10;
    private javax.swing.JCheckBox cbMenu2;
    private javax.swing.JCheckBox cbMenu3;
    private javax.swing.JCheckBox cbMenu4;
    private javax.swing.JCheckBox cbMenu5;
    private javax.swing.JCheckBox cbMenu6;
    private javax.swing.JCheckBox cbMenu7;
    private javax.swing.JCheckBox cbMenu8;
    private javax.swing.JCheckBox cbMenu9;
    private javax.swing.JPanel contPesanan1;
    private javax.swing.JPanel contPesanan2;
    private javax.swing.JTextField inpJumMenu1;
    private javax.swing.JTextField inpJumMenu10;
    private javax.swing.JTextField inpJumMenu2;
    private javax.swing.JTextField inpJumMenu3;
    private javax.swing.JTextField inpJumMenu4;
    private javax.swing.JTextField inpJumMenu5;
    private javax.swing.JTextField inpJumMenu6;
    private javax.swing.JTextField inpJumMenu7;
    private javax.swing.JTextField inpJumMenu8;
    private javax.swing.JTextField inpJumMenu9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kembalian;
    private javax.swing.JPanel left;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu10;
    private javax.swing.JLabel menu2;
    private javax.swing.JLabel menu3;
    private javax.swing.JLabel menu4;
    private javax.swing.JLabel menu5;
    private javax.swing.JLabel menu6;
    private javax.swing.JLabel menu7;
    private javax.swing.JLabel menu8;
    private javax.swing.JLabel menu9;
    private javax.swing.JTextArea pesananJumlah;
    private javax.swing.JTextArea pesananMenu;
    private javax.swing.JTextArea pesananTotal;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JTabbedPane tabMenu;
    private javax.swing.JPanel top;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
